name: Android_CI

on:
  push:
    branches:
      - test_case
jobs:
  build:

    runs-on: macos-latest

    steps:


      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedCheck --stacktrace

