name: Android_CI

on:
  push:
    branches:
      - test_case
jobs:
  build:

    runs-on: ubuntu-latest

    steps:


      - uses: reactivecircus/android-emulator-runner@v2
        run: bash ./gradlew connectedCheck --stacktrace


